@echo off
echo Launching Android Emulator (flutter_emulator)...
call flutter emulators --launch flutter_emulator
echo Waiting for emulator to boot...
timeout /t 10
echo Launching Ithaki...
flutter run -d emulator-5554
pause
